# Generated by Django 5.2 on 2025-04-26 02:49

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('inquiry_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'General')], default=0)),
                ('description', models.TextField(max_length=1500)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
