# Generated by Django 5.2 on 2025-04-26 02:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(blank=True, default=blog.models.generate_id, max_length=20, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(default='', max_length=200, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('draft', models.BooleanField(blank=True, default=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
            ],
        ),
    ]
